# Subindo um servidor MySQL com o Docker e Docker-Compose

version: '4.27.2'
services:
  mysql_206:
    container_name: mysql_sqlalchemy
    hostname: mysql_sqlalchemy
    image: mysql:8
    restart: always
    command:
      - --authentication-policy=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes:
      - ./mysql_sqlalchemy:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: senha
      MYSQL_DATABASE: bd_sqlalchemy
      MYSQL_USER: usuario
      MYSQL_PASSWORD: senha
      TZ: America/Sao_Paulo